services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: yournewpassword
      MYSQL_DATABASE: good_to_go
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: .
    container_name: backend-container
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: yournewpassword
      DB_NAME: good_to_go
    depends_on:
      - mysql

volumes:
  mysql-data:
